### ISSUE TITLE
Font size too small

### ISSUE THREAD

**Issue by rogerogers** [openkruise/openkruise.io#108]
https://github.com/openkruise/openkruise.io/blob/3e22aed86b0072c9645a4cf0f32531c6b2e786b7/src/css/custom.css#L58

Almost out of sight

**Comment by rogerogers** [comment]
![image](https://github.com/openkruise/openkruise.io/assets/40619032/877be389-c9e8-415a-9f72-f08a953143f5)

**Comment by furykerry** [comment]
a small problem, i will fix it today
